# Real-Time Facial Emotion Recognition using CNN

## Overview
This project implements a Convolutional Neural Network (CNN) to detect human emotions from facial expressions in real-time.

## Dataset
- FER-2013 dataset (35,000+ images)

## Model Architecture
- Convolutional Layers
- Batch Normalization
- MaxPooling
- Dropout
- Softmax Classifier

## Results
- Training Accuracy: 83.36%
- Test Accuracy: 65.67%

## Features
- Real-time emotion detection using webcam
- Image preprocessing and normalization
- Face detection using OpenCV

## Tech Stack
- Python
- TensorFlow / Keras
- OpenCV
- NumPy

## Author
Chunduri Sushen
